# Generated by Django 5.2.8 on 2025-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("car", "CAR"),
                            ("central", "Central Office"),
                            ("ncr", "NCR"),
                            ("negros", "Negros Island Region"),
                            ("1", "Region I"),
                            ("2", "Region II"),
                            ("3", "Region III"),
                            ("4.1", "Region IV-A"),
                            ("4.2", "Region IV-B"),
                            ("5", "Region V"),
                            ("6", "Region VI"),
                            ("7", "Region VII"),
                            ("8", "Region VIII"),
                            ("9", "Region IX"),
                            ("10", "Region X"),
                            ("11", "Region XI"),
                            ("12", "Region XII"),
                            ("13", "Region XIII"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("incomplete", "Incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=120)),
                ("photo", models.ImageField(upload_to="reports/")),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
