# Generated by Django 5.2 on 2025-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
